---
title: "DESeq2"
author: "Carla Batlle"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Càrrega de Paquets

```{r}
library(DESeq2)
library(dplyr)
library(org.Hs.eg.db)
library(annotate)
library(clusterProfiler)
library(ggpubr)
library(enrichplot)
library(ggplot2)
library(forcats)
library(ggupset)

```

## Configuració de Directori

```{r}
setwd("~/Documents/practiques/data")

```

## Càrrega de Dades

```{r}
countData <- read.csv("unproc_rnaseq.csv")
metaData <- read.csv('donor.csv', header = TRUE, sep = ",")
metaData

```

## Filtratge i Creació de l'Objecte DESeqDataSet

```{r}
filtered_df <- subset(metaData, record_id %in% colnames(countData))
dds <- DESeqDataSetFromMatrix(countData=countData, 
                              colData=filtered_df, 
                              design= ~ diagnosis, tidy = TRUE)
dds <- DESeq(dds)

```

## Resultats de l'Anàlisi DEG

```{r}
res <- results(dds)
head(results(dds, tidy=TRUE))

# Ordenar per p-valor ajustat
res <- res[order(res$padj),]
head(res)

# Filtrar per p.adj < 0.05
res_padj <- subset(res, padj < 0.05)
res_padj

```

## Anotació de Gens

```{r}
Change <- clusterProfiler::bitr(rownames(res_padj),
                                fromType = "ENTREZID",
                                toType = "SYMBOL",
                                OrgDb = org.Hs.eg.db,
                                drop = TRUE)
rownames(res_padj) <- Change$SYMBOL

```

## VolcanoPlot

```{r}
res_padj$diffexpressed <- "NO"
res_padj$diffexpressed[res_padj$log2FoldChange > 0.6 & res_padj$pvalue < 0.05] <- "UP"
res_padj$diffexpressed[res_padj$log2FoldChange < -0.6 & res_padj$pvalue < 0.05] <- "DOWN"

# Eliminació de valors NA
res_padj <- res_padj[!is.na(res_padj$log2FoldChange) & !is.na(res_padj$pvalue), ]

# Gràfic
ggplot(data = res_padj, aes(x = log2FoldChange, y = -log10(pvalue), col = diffexpressed)) +
  geom_vline(xintercept = c(-0.6, 0.6), col = "gray", linetype = 'dashed') +
  geom_hline(yintercept = -log10(0.05), col = "gray", linetype = 'dashed') +
  geom_point(size = 2) +
  scale_color_manual(values = c("#00AFBB", "grey", "#FFDB6D"), 
                     labels = c("Downregulated", "Not significant", "Upregulated")) +
  theme_minimal()

```

# Anàlisi Funcional
```{r}
signif_genes <- rownames(res_padj)

ego <- enrichGO(gene = signif_genes,
                keyType = "SYMBOL",
                OrgDb = org.Hs.eg.db,
                ont = "BP",
                pAdjustMethod = "BH",
                qvalueCutoff = 0.05)

# Simplificació de termes redundants
ego2 <- simplify(ego, cutoff = 0.7, by = "p.adjust", select_fun = min)

# Gràfics
barplot(ego2, showCategory = 10) +
  theme(axis.text.y = element_text(size = 8))

dotplot(ego2, showCategory = 10) +
  theme(axis.text.y = element_text(size = 8))

```

## Gene Set Enrichment Analysis (GSEA)
```{r}
geneList <- res_padj$log2FoldChange
names(geneList) <- rownames(res_padj)
geneList <- geneList[order(geneList, decreasing = TRUE)]

ggo <- gseGO(geneList, keyType = "SYMBOL",
             OrgDb = org.Hs.eg.db, pvalueCutoff = 1)
ggo2 <- simplify(ggo, cutoff = 0.7, by = "p.adjust", select_fun = min)

ggo2 <- pairwise_termsim(ggo2)

# Gràfics de GSEA
cnetplot(ego2, foldChange = geneList, showCategory = 2,
         cex_label_gene = 0.2,
         cex_label_category = 0.5)

heatplot(ggo2, foldChange = geneList, showCategory = 10) +
  theme(axis.text.x = element_text(angle = 90, size = 5))

upsetplot(ego, n = 5)

```
